name: 'Slack Release Scan Notification'
description: 'Send Slack notification for release scan results'
inputs:
  app_name:
    description: 'Application name'
    required: true
  repo:
    description: 'Application repository name (org/repo format)'
    required: true
  release_branch:
    description: 'Release branch scanned'
    required: true
  pr_created:
    description: 'Whether a PR was created'
    required: true
  pr_number:
    description: 'PR number if created or found'
    required: false
    default: ''
  pr_url:
    description: 'PR URL if created or found'
    required: false
    default: ''
  updated:
    description: 'Whether the application was updated'
    required: true
  new_version:
    description: 'New version of the application'
    required: false
    default: ''
  updates_cnt:
    description: 'Number of module updates'
    required: false
    default: '0'
  updated_modules:
    description: 'List of updated modules'
    required: false
    default: ''
  workflow_result:
    description: 'Result of the scan workflow (success/failure/skipped)'
    required: true
  workflow_run_id:
    description: 'GitHub run ID for linking'
    required: true
  workflow_run_number:
    description: 'GitHub run number for display'
    required: true
  error_message:
    description: 'Error message from the failed workflow'
    required: false
    default: ''
  successful_reviewers:
    description: 'Space-separated list of successfully added reviewers'
    required: false
    default: ''
  failed_reviewers:
    description: 'Space-separated list of reviewers that failed to be added'
    required: false
    default: ''
  slack_channel:
    description: 'Slack channel for notification'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true
outputs:
  notification_sent:
    description: 'Whether the notification was sent'
    value: ${{ steps.determine-status.outputs.notification_sent }}
  notification_status:
    description: 'Status of the notification'
    value: ${{ steps.determine-status.outputs.notification_status }}

runs:
  using: 'composite'
  steps:
    - name: Build Updated Modules Info
      id: updated-modules-info
      if: inputs.workflow_result == 'success' && inputs.updated == 'true' && inputs.updated_modules != ''
      shell: bash
      env:
        MODULES: "${{ inputs.updated_modules }}"
      run: |
        echo "::notice::Building updated modules info string"
        echo "updated_modules<<EOF"$'\n'"$MODULES"$'\n'EOF >> "$GITHUB_OUTPUT"

    - name: Build Reviewers List
      id: reviewers-list-info
      if: inputs.successful_reviewers != '' || inputs.failed_reviewers != ''
      shell: bash
      env:
        SUCCESSFUL_REVIEWERS: "${{ inputs.successful_reviewers }}"
        FAILED_REVIEWERS: "${{ inputs.failed_reviewers }}"
      run: |
        echo "::notice::Building reviewers list"

        if [ -n "$FAILED_REVIEWERS" ]; then
          REVIEWERS=$(echo "$FAILED_REVIEWERS" | tr ' ' '\n')
        elif [ -n "$SUCCESSFUL_REVIEWERS" ]; then
          REVIEWERS=$(echo "$SUCCESSFUL_REVIEWERS" | tr ' ' '\n')
        fi

        echo "reviewers<<EOF"$'\n'"$REVIEWERS"$'\n'EOF >> "$GITHUB_OUTPUT"

    - name: Send PR Created Notification
      id: send-pr-created
      if: inputs.workflow_result == 'success' && inputs.updated == 'true' && inputs.pr_created == 'true'
      continue-on-error: true
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        errors: false
        payload: |
          channel: "${{ inputs.slack_channel }}"
          text: "Release Scan: PR Created"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "*${{ inputs.app_name }} Release Scan: PR Created <${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ inputs.workflow_run_id }}|#${{ inputs.workflow_run_number }}>*"
          attachments:
            - color: "good"
              fields:
                - title: "Release Branch"
                  value: "<${{ github.server_url }}/${{ inputs.repo }}/tree/${{ inputs.release_branch }}|${{ inputs.release_branch }}>"
                  short: true
                - title: "New Version"
                  value: "${{ inputs.new_version }}"
                  short: true
                - title: "Updates Found"
                  value: "${{ inputs.updates_cnt }}"
                  short: true
                - title: "Pull Request"
                  value: "${{ inputs.pr_url != '' && format('<{0}|Created PR #{1}>', inputs.pr_url, inputs.pr_number) || 'No PR created' }}"
                  short: true
            - color: "good"
              mrkdwn_in: ["text"]
              text: ${{ toJSON(steps.updated-modules-info.outputs.updated_modules || inputs.updated_modules) }}
            - color: "${{ inputs.failed_reviewers != '' && 'warning' || 'good' }}"
              mrkdwn_in: ["text"]
              title: "${{ inputs.failed_reviewers != '' && 'Reviewers (failed)' || (inputs.successful_reviewers != '' && 'Reviewers (added)' || 'Reviewers') }}"
              text: ${{ toJSON(steps.reviewers-list-info.outputs.reviewers || 'No reviewers configured') }}
              footer: "Eureka CI/CD"

    - name: Send Branch Updated Notification
      id: send-branch-updated
      if: inputs.workflow_result == 'success' && inputs.updated == 'true' && inputs.pr_created != 'true'
      continue-on-error: true
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        errors: false
        payload: |
          channel: "${{ inputs.slack_channel }}"
          text: "Release Scan: Branch Updated"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "*${{ inputs.app_name }} Release Scan: Branch Updated <${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ inputs.workflow_run_id }}|#${{ inputs.workflow_run_number }}>*"
          attachments:
            - color: "good"
              fields:
                - title: "Release Branch"
                  value: "<${{ github.server_url }}/${{ inputs.repo }}/tree/${{ inputs.release_branch }}|${{ inputs.release_branch }}>"
                  short: true
                - title: "New Version"
                  value: "${{ inputs.new_version }}"
                  short: true
                - title: "Updates Found"
                  value: "${{ inputs.updates_cnt }}"
                  short: true
                - title: "Pull Request"
                  value: "${{ inputs.pr_url != '' && format('<{0}|Updated PR #{1}>', inputs.pr_url, inputs.pr_number) || 'Branch updated' }}"
                  short: true
            - color: "good"
              mrkdwn_in: ["text"]
              text: ${{ toJSON(steps.updated-modules-info.outputs.updated_modules || inputs.updated_modules) }}
              footer: "Eureka CI/CD"

    - name: Send Failure Notification
      id: send-failure
      if: inputs.workflow_result == 'failure'
      continue-on-error: true
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        errors: false
        payload: |
          channel: "${{ inputs.slack_channel }}"
          text: "Release Scan: Failed"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "*${{ inputs.app_name }} Release Scan: Failed <${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ inputs.workflow_run_id }}|#${{ inputs.workflow_run_number }}>*"
          attachments:
            - color: "danger"
              fields:
                - title: "Release Branch"
                  value: "<${{ github.server_url }}/${{ inputs.repo }}/tree/${{ inputs.release_branch }}|${{ inputs.release_branch }}>"
                  short: true
                - title: "Status"
                  value: "Workflow Failed"
                  short: true
                - title: "Error"
                  value: "${{ inputs.error_message != '' && inputs.error_message || 'Check workflow logs for details' }}"
                  short: false
              footer: "Eureka CI/CD"

    - name: Determine Status
      id: determine-status
      if: always()
      shell: bash
      run: |
        if [[ "${{ inputs.workflow_result }}" == "success" && "${{ inputs.updated }}" == "false" ]]; then
          echo "notification_sent=false" >> "$GITHUB_OUTPUT"
          echo "notification_status=skipped" >> "$GITHUB_OUTPUT"
          echo "::notice::No notification needed - no updates found"
        elif [[ "${{ steps.send-pr-created.outcome }}" == "success" ]] || \
             [[ "${{ steps.send-branch-updated.outcome }}" == "success" ]] || \
             [[ "${{ steps.send-failure.outcome }}" == "success" ]]; then
          echo "notification_sent=true" >> "$GITHUB_OUTPUT"
          echo "notification_status=success" >> "$GITHUB_OUTPUT"
          echo "::notice::Successfully sent notification to ${{ inputs.slack_channel }}"
        elif [[ "${{ steps.send-pr-created.outcome }}" == "failure" ]] || \
             [[ "${{ steps.send-branch-updated.outcome }}" == "failure" ]] || \
             [[ "${{ steps.send-failure.outcome }}" == "failure" ]]; then
          echo "notification_sent=false" >> "$GITHUB_OUTPUT"
          echo "notification_status=failure" >> "$GITHUB_OUTPUT"
          echo "::warning::Failed to send notification to ${{ inputs.slack_channel }}"
        else
          echo "notification_sent=false" >> "$GITHUB_OUTPUT"
          echo "notification_status=skipped" >> "$GITHUB_OUTPUT"
        fi