name: 'Check Protected Files'
description: 'Check for protected file violations (deletion of lock/template files)'

inputs:
  check_type:
    description: 'Type of check: pr or merge_queue'
    required: true
  repo_owner:
    description: 'Repository owner'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  pr_number:
    description: 'Pull request number (required for PR context)'
    required: false
  head_sha:
    description: 'Commit SHA (for logging in merge_queue context)'
    required: false
  github_token:
    description: 'GitHub token'
    required: true
  protected_lock_file:
    description: 'Lock file name to protect'
    required: false
    default: 'application.lock.json'
  protected_template_file:
    description: 'Template file name to protect'
    required: false
    default: 'application.template.json'

outputs:
  has_violations:
    description: 'Whether protected file violations were found'
    value: ${{ steps.check-pr.outputs.has_violations || steps.check-merge-queue.outputs.has_violations }}
  violations:
    description: 'Semicolon-separated violation messages'
    value: ${{ steps.check-pr.outputs.violations || steps.check-merge-queue.outputs.violations }}

runs:
  using: 'composite'
  steps:
    - name: Check Protected Files (PR)
      id: check-pr
      if: inputs.check_type == 'pr'
      uses: actions/github-script@v7
      env:
        PROTECTED_LOCK_FILE: ${{ inputs.protected_lock_file }}
        PROTECTED_TEMPLATE_FILE: ${{ inputs.protected_template_file }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const protectedLockFile = process.env.PROTECTED_LOCK_FILE;
          const protectedTemplateFile = process.env.PROTECTED_TEMPLATE_FILE;

          console.log(`Protected files: ${protectedLockFile} (deletion), ${protectedTemplateFile} (deletion)`);

          const { data: files } = await github.rest.pulls.listFiles({
            owner: '${{ inputs.repo_owner }}',
            repo: '${{ inputs.repo_name }}',
            pull_number: parseInt('${{ inputs.pr_number }}')
          });

          let violations = [];
          for (const file of files) {
            if (file.filename === protectedLockFile && file.status === 'removed') {
              violations.push(`${file.filename}: lock file deletion not allowed`);
            }
            if (file.filename === protectedTemplateFile && file.status === 'removed') {
              violations.push(`${file.filename}: template file deletion not allowed`);
            }
          }

          const hasViolations = violations.length > 0;
          core.setOutput('has_violations', hasViolations);
          core.setOutput('violations', violations.join('; '));

          if (hasViolations) {
            console.log(`Protected file violations found: ${violations.join(', ')}`);
          } else {
            console.log('No protected file violations found');
          }

    - name: Check Protected Files (Merge Queue)
      id: check-merge-queue
      if: inputs.check_type == 'merge_queue'
      shell: bash
      env:
        PROTECTED_LOCK_FILE: ${{ inputs.protected_lock_file }}
        PROTECTED_TEMPLATE_FILE: ${{ inputs.protected_template_file }}
      run: |
        echo "::notice::Checking protected files for merge queue commit using git diff"
        echo "::notice::Protected files: $PROTECTED_LOCK_FILE (deletion), $PROTECTED_TEMPLATE_FILE (deletion)"
        VIOLATIONS=""

        while IFS=$'\t' read -r STATUS FILE; do
          if [[ "$FILE" == "$PROTECTED_LOCK_FILE" ]] && [[ "$STATUS" == "D" ]]; then
            VIOLATIONS="${VIOLATIONS}${VIOLATIONS:+; }${FILE}: lock file deletion not allowed"
          fi
          if [[ "$FILE" == "$PROTECTED_TEMPLATE_FILE" ]] && [[ "$STATUS" == "D" ]]; then
            VIOLATIONS="${VIOLATIONS}${VIOLATIONS:+; }${FILE}: template file deletion not allowed"
          fi
        done < <(git diff --name-status HEAD~1 HEAD 2>/dev/null || echo "")

        if [ -n "$VIOLATIONS" ]; then
          echo "::error::Protected file violations found: $VIOLATIONS"
          echo "has_violations=true" >> "$GITHUB_OUTPUT"
          echo "violations=$VIOLATIONS" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::No protected file violations found"
          echo "has_violations=false" >> "$GITHUB_OUTPUT"
          echo "violations=" >> "$GITHUB_OUTPUT"
        fi