name: 'Generate Application Descriptor'
description: 'Generate or update application descriptor using folio-application-generator'

inputs:
  app_name:
    description: 'Application name'
    required: true
  state_file:
    description: 'Path to application state file (JSON)'
    required: false
    default: 'application.lock.json'
  template_file:
    description: 'Path to template file'
    required: false
    default: 'application.template.json'
  generation_mode:
    description: 'Mode: generate (from template) or update (from template to state file)'
    required: false
    default: 'update'
  validate_artifacts:
    description: 'Validate Docker/NPM artifacts exist before resolution'
    required: false
    default: 'true'
  build_number:
    description: 'Build number for snapshot versions'
    required: false
    default: ''
  use_project_version:
    description: 'When true, uses pom.xml version as base; when false, increments patch from descriptor version (update mode only)'
    required: false
    default: 'true'
  upload_artifact:
    description: 'Whether to upload the generated descriptor as an artifact'
    required: false
    default: 'true'
  artifact_name:
    description: 'Name for the uploaded artifact (defaults to app_name-descriptor)'
    required: false
  artifact_retention_days:
    description: 'Number of days to retain the artifact'
    required: false
    default: '1'
  upload_state_file:
    description: 'Whether to upload the generated descriptor as application.lock.json state file artifact'
    required: false
    default: 'true'
  state_file_artifact_name:
    description: 'Name for the state file artifact (defaults to app_name-state-file)'
    required: false
  generator_version:
    description: 'Version of folio-application-generator Maven plugin to use'
    required: false
    default: '1.3.0-SNAPSHOT'
  use_input_generator_version:
    description: 'When true, uses generator_version input; when false, uses version from pom.xml'
    required: false
    default: 'false'

outputs:
  generated:
    description: 'Whether descriptor was generated with changes (true only when new descriptor file was created)'
    value: ${{ steps.generate.outputs.generated }}
  descriptor_file:
    description: 'Name of generated descriptor file'
    value: ${{ steps.generate.outputs.descriptor_file }}
  descriptor_file_name:
    description: 'Name of descriptor file without extension'
    value: ${{ steps.generate.outputs.descriptor_file_name }}
  artifact_name:
    description: 'Name of the uploaded artifact'
    value: ${{ inputs.artifact_name || format('{0}-descriptor', inputs.app_name) }}
  state_file_artifact_name:
    description: 'Name of the state file artifact'
    value: ${{ inputs.state_file_artifact_name || format('{0}-state-file', inputs.app_name) }}
  failure_reason:
    description: 'Reason for failure if generation failed'
    value: ${{ steps.validate-template.outputs.failure_reason || steps.generate.outputs.failure_reason }}
  updates_cnt:
    description: 'Total number of module changes (update mode only)'
    value: ${{ steps.parse-results.outputs.updates_cnt }}
  be_added:
    description: 'Backend modules added'
    value: ${{ steps.parse-results.outputs.be_added }}
  be_upgraded:
    description: 'Backend modules upgraded'
    value: ${{ steps.parse-results.outputs.be_upgraded }}
  be_downgraded:
    description: 'Backend modules downgraded'
    value: ${{ steps.parse-results.outputs.be_downgraded }}
  be_removed:
    description: 'Backend modules removed'
    value: ${{ steps.parse-results.outputs.be_removed }}
  ui_added:
    description: 'UI modules added'
    value: ${{ steps.parse-results.outputs.ui_added }}
  ui_upgraded:
    description: 'UI modules upgraded'
    value: ${{ steps.parse-results.outputs.ui_upgraded }}
  ui_downgraded:
    description: 'UI modules downgraded'
    value: ${{ steps.parse-results.outputs.ui_downgraded }}
  ui_removed:
    description: 'UI modules removed'
    value: ${{ steps.parse-results.outputs.ui_removed }}
  updated_modules:
    description: 'Summary of all module changes'
    value: ${{ steps.parse-results.outputs.updated_modules }}

runs:
  using: 'composite'
  steps:
    - name: Validate Template Versions
      id: validate-template
      shell: bash
      env:
        TEMPLATE_FILE: ${{ inputs.template_file }}
      run: |
        set -eo pipefail

        echo "::notice::Validating module versions in $TEMPLATE_FILE"

        if [[ ! -f "$TEMPLATE_FILE" ]]; then
          echo "::error::Template file not found: $TEMPLATE_FILE"
          echo "failure_reason=Template file not found: $TEMPLATE_FILE" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        SEMVER_PATTERN='^(latest|(\^|~|>=|>|<=|<|=)?v?[0-9]+(\.[0-9]+)?(\.[0-9]+)?(-[a-zA-Z0-9._-]+)?(\+[a-zA-Z0-9._-]+)?( (>=|>|<=|<)?[0-9]+(\.[0-9]+)?(\.[0-9]+)?(-[a-zA-Z0-9._-]+)?)?)$'

        invalid_modules=""
        while IFS= read -r line; do
          name=$(echo "$line" | cut -d'|' -f1)
          version=$(echo "$line" | cut -d'|' -f2)
          if [[ -n "$version" && ! "$version" =~ $SEMVER_PATTERN ]]; then
            invalid_modules+="$name: $version"$'\n'
          fi
        done < <(jq -r '([.modules[]? | "\(.name)|\(.version)"], [.uiModules[]? | "\(.name)|\(.version)"]) | .[]' "$TEMPLATE_FILE")

        if [[ -n "$invalid_modules" ]]; then
          echo "::warning::Invalid module versions in template (must be semver, semver range, or 'latest') - skipping update:"
          while IFS= read -r m; do
            if [[ -n "$m" ]]; then
              echo "::warning::  - $m"
            fi
          done <<< "$invalid_modules"
          echo "valid=false" >> "$GITHUB_OUTPUT"
          echo "failure_reason=Invalid module versions in template: $(echo "$invalid_modules" | tr '\n' ', ' | sed 's/, $//')" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "valid=true" >> "$GITHUB_OUTPUT"
        echo "::notice::All module versions are valid semver/semver range"

    - name: Determine Generation Mode
      id: determine-mode
      shell: bash
      env:
        GENERATION_MODE: ${{ inputs.generation_mode }}
        STATE_FILE: ${{ inputs.state_file }}
      run: |
        if [[ "$GENERATION_MODE" == "update" && ! -f "$STATE_FILE" ]]; then
          echo "::notice::State file not found ($STATE_FILE), using generate mode"
          echo "mode=generate" >> "$GITHUB_OUTPUT"
        else
          echo "mode=$GENERATION_MODE" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate Application Descriptor
      id: generate
      if: steps.validate-template.outputs.valid == 'true'
      shell: bash
      env:
        APP_NAME: ${{ inputs.app_name }}
        STATE_FILE: ${{ inputs.state_file }}
        GENERATION_MODE: ${{ steps.determine-mode.outputs.mode }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
        VALIDATE_ARTIFACTS: ${{ inputs.validate_artifacts }}
        BUILD_NUMBER: ${{ inputs.build_number }}
        USE_PROJECT_VERSION: ${{ inputs.use_project_version }}
        GENERATOR_VERSION: ${{ inputs.generator_version }}
        USE_INPUT_GENERATOR_VERSION: ${{ inputs.use_input_generator_version }}
        SUPPRESS_LOGS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      run: |
        set -eo pipefail

        if [[ ! -f "pom.xml" ]]; then
          echo "::error::pom.xml not found"
          echo "generated=false" >> "$GITHUB_OUTPUT"
          exit 1
        fi
        
        if [[ ! -f "$TEMPLATE_FILE" ]]; then
          echo "::error::Template file not found: $TEMPLATE_FILE"
          echo "generated=false" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        if [[ "$USE_INPUT_GENERATOR_VERSION" == "true" ]]; then
          PLUGIN_COORD="org.folio:folio-application-generator:${GENERATOR_VERSION}"
        else
          PLUGIN_COORD="org.folio:folio-application-generator"
        fi

        if [[ "$GENERATION_MODE" == "update" ]]; then
          COMMAND="${PLUGIN_COORD}:updateFromTemplate"
          EXTRA_PARAMS="-DappDescriptorPath=$STATE_FILE -DtemplatePath=$TEMPLATE_FILE"
        else
          COMMAND="${PLUGIN_COORD}:generateFromJson"
          EXTRA_PARAMS="-DtemplatePath=$TEMPLATE_FILE"
        fi

        if [[ "$VALIDATE_ARTIFACTS" == "true" ]]; then
          EXTRA_PARAMS+=" -DvalidateArtifacts=true"
        fi

        if [[ -n "$BUILD_NUMBER" ]]; then
          EXTRA_PARAMS+=" -DbuildNumber=$BUILD_NUMBER"
        fi

        if [[ "$GENERATION_MODE" == "update" && "$USE_PROJECT_VERSION" == "true" ]]; then
          EXTRA_PARAMS+=" -DuseProjectVersion=true"
        fi

        echo "::notice::Running $GENERATION_MODE mode"
        echo "::notice::Full Maven command: mvn $SUPPRESS_LOGS clean $COMMAND -U -e $EXTRA_PARAMS"
        echo "::group::Generate application descriptor"
        mvn $SUPPRESS_LOGS clean $COMMAND -U -e $EXTRA_PARAMS
        echo "::endgroup::"

        if [[ ! -d "target" ]]; then
          echo "::notice::No changes detected - target directory was not created by Maven"
          echo "generated=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "::group::Debug - Check target directory contents"
        ls -la target/
        echo "::endgroup::"

        APP_DESCRIPTOR_FILE=$(compgen -G "target/${APP_NAME}*.json" | grep -v "update-result" | head -n 1 || true)
        if [[ -z "$APP_DESCRIPTOR_FILE" ]]; then
          echo "::error::Generated application descriptor not found in target directory"
          echo "generated=false" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        APP_DESCRIPTOR_FILENAME=$(basename "$APP_DESCRIPTOR_FILE")
        echo "generated=true" >> "$GITHUB_OUTPUT"
        echo "descriptor_file=$APP_DESCRIPTOR_FILENAME" >> "$GITHUB_OUTPUT"
        echo "descriptor_file_name=${APP_DESCRIPTOR_FILENAME%.json}" >> "$GITHUB_OUTPUT"

        echo "::notice::Application descriptor generated successfully: $APP_DESCRIPTOR_FILENAME"

    - name: Parse Update Results
      id: parse-results
      if: steps.generate.outputs.generated == 'true'
      shell: bash
      env:
        GENERATION_MODE: ${{ steps.determine-mode.outputs.mode }}
        APP_NAME: ${{ inputs.app_name }}
      run: |
        set -eo pipefail

        RESULT_FILE="target/update-result.json"

        be_added="" be_upgraded="" be_downgraded="" be_removed=""
        ui_added="" ui_upgraded="" ui_downgraded="" ui_removed=""
        total=0

        if [[ "$GENERATION_MODE" == "update" && -f "$RESULT_FILE" ]]; then
          echo "::group::Update Results"
          cat "$RESULT_FILE"
          echo "::endgroup::"
          be_added=$(jq -r '.beAdded // [] | join(", ")' "$RESULT_FILE")
          be_upgraded=$(jq -r '.beUpgraded // [] | join(", ")' "$RESULT_FILE")
          be_downgraded=$(jq -r '.beDowngraded // [] | join(", ")' "$RESULT_FILE")
          be_removed=$(jq -r '.beRemoved // [] | join(", ")' "$RESULT_FILE")
          ui_added=$(jq -r '.uiAdded // [] | join(", ")' "$RESULT_FILE")
          ui_upgraded=$(jq -r '.uiUpgraded // [] | join(", ")' "$RESULT_FILE")
          ui_downgraded=$(jq -r '.uiDowngraded // [] | join(", ")' "$RESULT_FILE")
          ui_removed=$(jq -r '.uiRemoved // [] | join(", ")' "$RESULT_FILE")
          total=$(jq '[(.beAdded // []), (.beUpgraded // []), (.beDowngraded // []), (.beRemoved // []), (.uiAdded // []), (.uiUpgraded // []), (.uiDowngraded // []), (.uiRemoved // []) | length] | add' "$RESULT_FILE")
        else
          DESCRIPTOR=$(compgen -G "target/${APP_NAME}*.json" | grep -v "update-result" | head -n 1)
          if [[ -f "$DESCRIPTOR" ]]; then
            be_added=$(jq -r '[.modules[]? | "\(.name)-\(.version)"] | join(", ")' "$DESCRIPTOR")
            ui_added=$(jq -r '[.uiModules[]? | "\(.name)-\(.version)"] | join(", ")' "$DESCRIPTOR")
            total=$(jq '([.modules // [] | length] + [.uiModules // [] | length]) | add' "$DESCRIPTOR")
          fi
        fi

        echo "be_added=$be_added" >> "$GITHUB_OUTPUT"
        echo "be_upgraded=$be_upgraded" >> "$GITHUB_OUTPUT"
        echo "be_downgraded=$be_downgraded" >> "$GITHUB_OUTPUT"
        echo "be_removed=$be_removed" >> "$GITHUB_OUTPUT"
        echo "ui_added=$ui_added" >> "$GITHUB_OUTPUT"
        echo "ui_upgraded=$ui_upgraded" >> "$GITHUB_OUTPUT"
        echo "ui_downgraded=$ui_downgraded" >> "$GITHUB_OUTPUT"
        echo "ui_removed=$ui_removed" >> "$GITHUB_OUTPUT"
        echo "updates_cnt=$total" >> "$GITHUB_OUTPUT"

        if [[ $total -gt 0 ]]; then
          echo "updated=true" >> "$GITHUB_OUTPUT"
        else
          echo "updated=false" >> "$GITHUB_OUTPUT"
        fi

        updated_modules=""
        [[ -n "$be_added" ]] && updated_modules+="BE Added: $be_added"$'\n'
        [[ -n "$be_upgraded" ]] && updated_modules+="BE Upgraded: $be_upgraded"$'\n'
        [[ -n "$be_downgraded" ]] && updated_modules+="BE Downgraded: $be_downgraded"$'\n'
        [[ -n "$be_removed" ]] && updated_modules+="BE Removed: $be_removed"$'\n'
        [[ -n "$ui_added" ]] && updated_modules+="UI Added: $ui_added"$'\n'
        [[ -n "$ui_upgraded" ]] && updated_modules+="UI Upgraded: $ui_upgraded"$'\n'
        [[ -n "$ui_downgraded" ]] && updated_modules+="UI Downgraded: $ui_downgraded"$'\n'
        [[ -n "$ui_removed" ]] && updated_modules+="UI Removed: $ui_removed"$'\n'

        echo "updated_modules<<EOF" >> "$GITHUB_OUTPUT"
        echo "$updated_modules" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "::notice::Total module changes: $total"

    - name: Upload Descriptor Artifact
      if: steps.generate.outputs.generated == 'true' && inputs.upload_artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.artifact_name || format('{0}-descriptor', inputs.app_name) }}"
        path: "target/${{ inputs.app_name }}*.json"
        retention-days: ${{ inputs.artifact_retention_days }}

    - name: Prepare State File
      if: steps.generate.outputs.generated == 'true' && inputs.upload_state_file == 'true'
      shell: bash
      run: |
        mkdir -p /tmp/state-file-upload
        cp "target/${{ steps.generate.outputs.descriptor_file }}" /tmp/state-file-upload/application.lock.json

    - name: Upload State File Artifact
      if: steps.generate.outputs.generated == 'true' && inputs.upload_state_file == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.state_file_artifact_name || format('{0}-state-file', inputs.app_name) }}"
        path: /tmp/state-file-upload/application.lock.json
        retention-days: ${{ inputs.artifact_retention_days }}