name: 'Check Run Create'
description: 'Create a GitHub check run for eureka-ci / validate-application with unified messaging'

inputs:
  repo_owner:
    description: 'Repository owner'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  head_sha:
    description: 'Commit SHA'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  has_violations:
    description: 'Whether protected file violations were found'
    required: true
  violations:
    description: 'Violation messages (if any)'
    required: false
    default: ''
  details_url:
    description: 'URL to workflow run'
    required: true

outputs:
  check_run_id:
    description: 'Created check run ID'
    value: ${{ steps.create-check.outputs.check_run_id }}

runs:
  using: 'composite'
  steps:
    - name: Create Check Run
      id: create-check
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const hasViolations = '${{ inputs.has_violations }}' === 'true';
          const violations = '${{ inputs.violations }}';

          const title = hasViolations
            ? 'Protected File Violation'
            : 'Non-Update Approved';

          const summary = hasViolations
            ? `This commit modifies protected files:\n${violations.split('; ').join('\n')}`
            : 'This is not an update. Validation skipped, can proceed.';

          const { data: checkRun } = await github.rest.checks.create({
            owner: '${{ inputs.repo_owner }}',
            repo: '${{ inputs.repo_name }}',
            name: 'eureka-ci / validate-application',
            head_sha: '${{ inputs.head_sha }}',
            status: 'completed',
            conclusion: hasViolations ? 'failure' : 'success',
            completed_at: new Date().toISOString(),
            output: {
              title: title,
              summary: summary
            },
            details_url: '${{ inputs.details_url }}'
          });

          core.setOutput('check_run_id', checkRun.id);
          console.log(`Check run created with ID ${checkRun.id} and conclusion: ${hasViolations ? 'failure' : 'success'}`);