name: Application Update Slack Notification

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Application name'
        required: true
        type: string
      repo:
        description: 'Application repository name (org/repo format)'
        required: true
        type: string
      branch:
        description: 'Branch to update'
        required: false
        type: string
        default: 'snapshot'
      new_version:
        description: 'Application new version'
        required: true
        type: string
      previous_version:
        description: 'Application previous version'
        required: true
        type: string
      updated_cnt:
        description: 'Number of updated modules'
        required: false
        type: string
        default: ''
      updated_modules:
        description: 'List of updated modules'
        required: false
        type: string
        default: ''
      updated_modules_b64:
        description: 'List of updated modules in base64'
        required: false
        type: string
        default: ''
      failure_reason:
        description: 'Reason for failure if applicable'
        required: false
        type: string
        default: ''
      commit_sha:
        description: 'Commit SHA of the release'
        required: true
        type: string
      workflow_result:
        description: 'Result of the main workflow (success/failure)'
        required: true
        type: string
      workflow_run_id:
        description: 'GitHub run ID for linking'
        required: true
        type: string
      workflow_run_number:
        description: 'GitHub run number for display'
        required: true
        type: string
      slack_notif_channel:
        description: 'Slack notification channel'
        required: true
        type: string

jobs:
  send-notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.EUREKA_CI_SLACK_BOT_TOKEN }}
      SLACK_NOTIF_CHANNEL: ${{ vars.GENERAL_SLACK_NOTIF_CHANNEL }}  # TODO: Switch to ${{ inputs.slack_notif_channel }} before merging to master
    steps:
      - name: Decode updated modules
        id: decode-updated-modules
        run: |
          set -eo pipefail
          
          decoded="$(printf '%s' "${{ inputs.updated_modules_b64 }}" | base64 -d)"

          delim="EOF_$(date +%s%N)"

          {
            printf 'UPDATED_MODULES<<%s\n' "$delim"
            printf '%s\n' "$decoded"
            printf '%s\n' "$delim"
          } >> "$GITHUB_ENV"

      - name: Prepare updated modules for Slack message
        id: prepare-updated-modules
        env:
          MODULES: "${{ inputs.updated_modules }}"
        run: |
          set -eo pipefail
          
          {
            echo 'UPDATED_MODULES_2<<EOF'
            printf '%s\n' "$MODULES"
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Build multiline string
        run: |
          updated_modules=""
          updated_modules+="app-core 1.2.3 -> 1.4.0"$'\n'
          updated_modules+="app-ui 2.0.0 -> 2.1.1"

          {
            echo "UPDATED_MODULES_3<<EOF"
            printf "%s\n" "$updated_modules"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Send SUCCESS Slack Notification
        if: inputs.workflow_result == 'success'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ env.SLACK_BOT_TOKEN }}
          errors: true
          payload: |
            channel: "${{ env.SLACK_NOTIF_CHANNEL }}"
            text: "Application Update SUCCESS"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "*${{ inputs.app_name }} Application Update SUCCESS <${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ inputs.workflow_run_id }}|#${{ inputs.workflow_run_number }}>*"
              - type: section
                text:
                  type: mrkdwn
                  text: >-
                    ${{
                        format(
                          'Reason: Update failed
                     Failed module(s): {0}', inputs.updated_modules
                        )
                    }}            
            attachments:
              - color: "good"
                fields:
                  - title: "New Version"
                    value: "${{ inputs.new_version }}"
                    short: true
                  - title: "Previous Version"
                    value: "${{ inputs.previous_version }}"
                    short: true                    
                  - title: "Updated"
                    value: "${{ inputs.updated_cnt }}"
                    short: true                   
                  - title: "Commit"
                    value: "<${{ github.server_url }}/${{ inputs.repo }}/commit/${{ inputs.commit_sha }}|${{ inputs.commit_sha }}>"
                    short: true
              - color: "good"
                mrkdwn_in: ["fields"]
                fields:
                  - title: "Updated Modules"
                    value: "```${{ inputs.updated_modules }}```"
                    short: false
              - color: "good"
                mrkdwn_in: ["fields"]
                fields:
                  - title: "Updated Modules"
                    value: "```${{ env.UPDATED_MODULES }}```"
                    short: false
              - color: "good"
                mrkdwn_in: ["fields"]
                fields:
                  - title: "Updated Modules"
                    value: "${{ env.UPDATED_MODULES_2 }}"
                    short: false
              - color: "good"
                mrkdwn_in: ["fields"]
                fields:
                  - title: "Updated Modules"
                    value: "${{ env.UPDATED_MODULES_3 }}"
                    short: false
                footer: "Eureka CI/CD"

      - name: Send FAILED Slack Notification
        if: inputs.workflow_result == 'failure'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ env.SLACK_BOT_TOKEN }}
          errors: true
          payload: |
            channel: "${{ env.SLACK_NOTIF_CHANNEL }}"
            text: "Application Update FAILED"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "*${{ inputs.app_name }} Application Update FAILED <${{ github.server_url }}/${{ inputs.app_name }}/actions/runs/${{ inputs.workflow_run_id }}|#${{ inputs.workflow_run_number }}>*"
            attachments:
              - color: "danger"
                fields:
                  - title: "Reason"
                    value: "${{ inputs.failure_reason }}"
                    short: false                  
                footer: "Eureka CI/CD"
