name: Create Pull Request (Reusable)

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository (org/repo format)'
        required: true
        type: string
      base_branch:
        description: 'Base branch for PR'
        required: true
        type: string
      head_branch:
        description: 'Head branch for PR'
        required: true
        type: string
      pr_title:
        description: 'Pull request title'
        required: true
        type: string
      pr_body:
        description: 'Pull request body (supports multiline)'
        required: true
        type: string
      pr_labels:
        description: 'Comma-separated list of labels'
        required: false
        type: string
        default: ''
    outputs:
      created:
        description: 'Whether a new PR was created'
        value: ${{ jobs.manage-pr.outputs.pr_created }}
      number:
        description: 'Pull request number'
        value: ${{ jobs.manage-pr.outputs.pr_number }}
      url:
        description: 'Pull request URL'
        value: ${{ jobs.manage-pr.outputs.pr_url }}

permissions:
  pull-requests: write
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  manage-pr:
    name: Manage Pull Request
    runs-on: ubuntu-latest
    outputs:
      pr_created: ${{ steps.check-existing-pr.outputs.existing_pr == '' && steps.create-pr.outputs.pr_number != '' }}
      pr_number: ${{ steps.check-existing-pr.outputs.existing_pr || steps.create-pr.outputs.pr_number || '' }}
      pr_url: ${{ steps.check-existing-pr.outputs.existing_pr_url || steps.create-pr.outputs.pr_url || '' }}
    steps:
      - name: Check existing PR
        id: check-existing-pr
        env:
          REPO: ${{ inputs.repo }}
          BASE_BRANCH: ${{ inputs.base_branch }}
          HEAD_BRANCH: ${{ inputs.head_branch }}
          PR_LABELS: ${{ inputs.pr_labels }}
        run: |
          set -eo pipefail
          
          echo "::notice::Check for existing PR"

          label_args=""
          if [ -n "$PR_LABELS" ]; then
            IFS=',' read -ra LABELS <<< "$PR_LABELS"
            for label in "${LABELS[@]}"; do
              label_args="$label_args --label \"$(echo $label | xargs)\""
            done
          fi

          pr_cmd="gh pr list \
            --repo "$REPO" \
            --base "$BASE_BRANCH" \
            --head "$HEAD_BRANCH" \
            --json number,url \
            --jq '.[0]'"
          
          if [ -n "$label_args" ]; then
            pr_cmd="$pr_cmd $label_args || echo '{}'"
          fi
          
          echo "::notice::Checking for existing PR with command: $pr_cmd"
          
          pr_json=$(eval $pr_cmd || echo '{}')
          
          if [ "$pr_json" != "{}" ] && [ -n "$pr_json" ]; then
            existing_pr=$(echo "$pr_json" | jq -r '.number // ""')
            existing_pr_url=$(echo "$pr_json" | jq -r '.url // ""')
            echo "::notice::Found existing PR #$existing_pr: $existing_pr_url"
          else
            existing_pr=""
            existing_pr_url=""
            echo "::notice::No existing PR found"
          fi
          
          echo "existing_pr=$existing_pr" >> "$GITHUB_OUTPUT"
          echo "existing_pr_url=$existing_pr_url" >> "$GITHUB_OUTPUT"
          echo "label_args=$label_args" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        id: create-pr
        if: steps.check-existing-pr.outputs.existing_pr == ''
        env:
          REPO: ${{ inputs.repo }}
          BASE_BRANCH: ${{ inputs.base_branch }}
          HEAD_BRANCH: ${{ inputs.head_branch }}
          TITLE: ${{ inputs.pr_title }}
          BODY: ${{ inputs.pr_body }}
          PR_LABELS: ${{ steps.check-existing-pr.outputs.label_args }}
        run: |
          set -eo pipefail
          
          echo "::notice::Creating new PR"
          
          pr_body_file=$(mktemp)
          echo "$BODY" > "$pr_body_file"

          pr_cmd="gh pr create \
            --repo \"$REPO\" \
            --base \"$BASE_BRANCH\" \
            --head \"$HEAD_BRANCH\" \
            --title \"$TITLE\" \
            --body-file \"$pr_body_file\""
          
          if [ -n "$PR_LABELS" ]; then
            pr_cmd="$pr_cmd $PR_LABELS"
          fi
          
          echo "::notice::Creating PR with command: $pr_cmd"

          pr_url=$(eval $pr_cmd)
            
          rm -f "$pr_body_file"
            
          pr_number=$(echo "$pr_url" | grep -oE '[0-9]+$')
            
          echo "pr_created=true" >> "$GITHUB_OUTPUT"
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
          echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
          
          echo "::notice::Successfully created PR #$pr_number"
